export namespace VESAVirtualControls {
  export const UsagePage = () => 0x82;
}

export enum VESAVirtualControls {
  Degauss = 0x01,
  Brightness = 0x10,
  Contrast = 0x12,
  RedVideoGain = 0x16,
  GreenVideoGain = 0x18,
  BlueVideoGain = 0x1A,
  Focus = 0x1C,
  HorizontalPosition = 0x20,
  HorizontalSize = 0x22,
  HorizontalPincushion = 0x24,
  HorizontalPincushionBalance = 0x26,
  HorizontalMisconvergence = 0x28,
  HorizontalLinearity = 0x2A,
  HorizontalLinearityBalance = 0x2C,
  VerticalPosition = 0x30,
  VerticalSize = 0x32,
  VerticalPincushion = 0x34,
  VerticalPincushionBalance = 0x36,
  VerticalMisconvergence = 0x38,
  VerticalLinearity = 0x3A,
  VerticalLinearityBalance = 0x3C,
  ParallelogramDistortion = 0x40,
  TrapezoidalDistortion = 0x42,
  Tilt = 0x44,
  TopCornerDistortionControl = 0x46,
  TopCornerDistortionBalance = 0x48,
  BottomCornerDistortionControl = 0x4A,
  BottomCornerDistortionBalance = 0x4C,
  HorizontalMoire = 0x56,
  VerticalMoire = 0x58,
  InputLevelSelect = 0x5E,
  InputSourceSelect = 0x60,
  RedVideoBlackLevel = 0x6C,
  GreenVideoBlackLevel = 0x6E,
  BlueVideoBlackLevel = 0x70,
  AutoSizeCenter = 0xA2,
  PolarityHorizontalSynchronization = 0xA4,
  PolarityVerticalSynchronization = 0xA6,
  SynchronizationType = 0xA8,
  ScreenOrientation = 0xAA,
  HorizontalFrequency = 0xAC,
  VerticalFrequency = 0xAE,
  Settings = 0xB0,
  OnScreenDisplay = 0xCA,
  StereoMode = 0xD4,
}